# Generated by Django 2.2.3 on 2019-07-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account1',
        ),
        migrations.DeleteModel(
            name='Account2',
        ),
        migrations.DeleteModel(
            name='Account3',
        ),
    ]
